Controllers/BugController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Web;
using System.Linq;
using System.Threading.Tasks;
using bugzilla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bugzilla.Controllers
{
    public class BugController : Controller
    {
        private readonly BugzillaDbContext _context;

        public BugController(BugzillaDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return RedirectToAction("Table");
        }

        public async Task<IActionResult> Table(Guid? dev, string? closed)
        {
            ViewData["bugs"] = await _context.Bugs
                .Include(bug => bug.Dev)
                .Include(bug => bug.Dev.Role)
                .ToListAsync();
            if (dev == null || closed == null)
                return View(await _context.Bugs.ToListAsync());

            var bugs = (IEnumerable<Bug>) await _context.Bugs.ToListAsync();
            if (dev != Guid.Empty)
            {
                bugs = bugs.Where(bug => bug.Dev.Id == dev);
            }

            switch (closed)
            {
                case "open":
                {
                    bugs = bugs.Where(bug => bug.Closed == false);
                    break;
                }
                case "closed":
                {
                    bugs = bugs.Where(bug => bug.Closed == true);
                    break;
                }
                    default:break;
            }

            return View(bugs);
        }

        public async Task<IActionResult> AddOrEdit(Guid? guid)
        {
            ViewData["bug"] = await _context.Bugs.FirstOrDefaultAsync(i => i.Id == guid);
            ViewData["devs"] = await _context.Developers.ToListAsync();
            return guid != null
                ? View(await _context.Bugs.FirstOrDefaultAsync(i => i.Id == guid))
                : View(new Bug {Id = Guid.NewGuid(), Description = "", Closed = false, Dev = null});
        }


        public async Task<IActionResult> Delete(Guid guid)
        {
            var bug = await _context.Bugs.FirstOrDefaultAsync(i => i.Id == guid);
            if (bug == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                _context.Bugs.Remove(bug);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException e)
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> AddOrEditDb(Guid id, Guid dev, string description, bool closed)
        {
            var bugToUpdate = await _context.Bugs.FindAsync(id);
            var developer = await _context.Developers.FindAsync(dev);
            if (bugToUpdate == null)
            {
                bugToUpdate = new Bug {Id = id, Description = description, Dev = developer, Closed = closed};
                await _context.Bugs.AddAsync(bugToUpdate);
            }
            else
            {
                bugToUpdate.Description = description;
                bugToUpdate.Dev = developer;
                bugToUpdate.Closed = closed;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/DeveloperController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using bugzilla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Crypto.Digests;

namespace bugzilla.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly BugzillaDbContext _context;

        public DeveloperController(BugzillaDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return RedirectToAction("Table");
        }

        public async Task<IActionResult> Table(Guid? role)
        {
            ViewData["devs"] = await _context.Developers.Include(dev => dev.Role).ToListAsync();
            return role == null
                ? View(await _context.Developers.ToListAsync())
                : View(await _context.Developers.Where(developer => developer.Role.Id == role).ToListAsync());
        }

        public async Task<IActionResult> AddOrEdit(Guid? id)
        {
            ViewData["roles"] = await _context.Roles.ToListAsync();
            if (id != null) return View(await _context.Developers.FindAsync(id));
            var dev = new Developer {Id = Guid.NewGuid(), Name = "", Role = null};
            return View(dev);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var developer = await _context.Developers.FirstOrDefaultAsync(i => i.Id == id);
            if (developer == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                _context.Developers.Remove(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException e)
            {
                //Log the error (uncomment ex variable name and write a log.)
                Console.WriteLine(e);
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> AddOrEditDb(Guid id, string name, Guid role)
        {
            var developerToUpdate = await _context.Developers.FindAsync(id);

            if (developerToUpdate == null)
            {
                developerToUpdate = new Developer {Id = id, Name = name, Role = await _context.Roles.FindAsync(role)};
                await _context.Developers.AddAsync(developerToUpdate);
            }
            else
            {
                developerToUpdate.Name = name;
                developerToUpdate.Role = await _context.Roles.FindAsync(role);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/FixController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bugzilla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bugzilla.Controllers
{
    public class FixController : Controller
    {
        private readonly BugzillaDbContext _context;

        public FixController(BugzillaDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return RedirectToAction("Table");
        }

        public async Task<IActionResult> Table(Guid? fixer, Guid? bug)
        {
            ViewData["reviews"] = await _context.Reviews.Include(i => i.Fix).ToListAsync();
            ViewData["fixes"] = await _context.Fixes
                .Include(fix => fix.Bug)
                .Include(fix => fix.Bug.Dev)
                .Include(fix => fix.Bug.Dev.Role)
                .Include(fix => fix.Dev)
                .Include(fix => fix.Dev.Role)
                .ToListAsync();
            if (fixer == null || bug == null)
                return View(await _context.Fixes.ToListAsync());

            var fixes = (IEnumerable<Fix>) await _context.Fixes.ToListAsync();

            fixes = bug == Guid.Empty ? fixes : fixes.Where(fix => fix.Bug.Id == bug);
            fixes = fixer == Guid.Empty ? fixes : fixes.Where(fix => fix.Dev.Id == fixer);

            return View(fixes);
        }

        public async Task<IActionResult> Add()
        {
            ViewData["fixes"] = await _context.Fixes.Include(fix => fix.Bug).Include(fix => fix.Dev).ToListAsync();
            ViewData["devs"] = await _context.Developers.ToListAsync();
            ViewData["bugs"] = await _context.Bugs.ToListAsync();
            return View();
        }

        public async Task<IActionResult> AddDb(Guid dev, Guid bug)
        {
            var developer = await _context.Developers.FindAsync(dev);
            var bugger = await _context.Bugs.FindAsync(bug);
            var fix = new Fix {Bug = bugger, Dev = developer, Id = Guid.NewGuid()};

            try
            {
                await _context.Fixes.AddAsync(fix);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException e)
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var fix = await _context.Fixes.FindAsync(id);
            if (fix == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                _context.Fixes.Remove(fix);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException e)
            {
                //Log the error (uncomment ex variable name and write a log.)
                Console.WriteLine(e);
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - bugzilla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bugzilla</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Developer" asp-action="Index">Developers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Bug" asp-action="Index">Bugs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Fix" asp-action="Index">Fixes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - bugzilla - <a asp-area="" asp-controller="Home" asp-action="Login">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>